function [SDR,factor] = sdr_initial(config)

switch config.sdr.type
    case 'rtl'  % Create RTL SDR receiver
        
        SDR = comm.SDRRTLReceiver(...
            'CenterFrequency', config.sdr.fc, ...
            'EnableTunerAGC',  false, ...
            'TunerGain',    config.sdr.gain,...
            'SampleRate',      config.sdr.FrontEndSampleRate, ...
            'SamplesPerFrame', config.FrameLength, ...
            'OutputDataType',  'double');
        %                 fprintf('sdr init\n');
        factor = 0;
    case 'n210' % Create USRP SDR receiver
        
        address = '192.168.10.2'; % IP address of the USRP
        platform = 'N200/N210/USRP2';
        MasterClockRate = 100e6; % 100 MHz
        % Baseband sample rate = Master clock rate/Decimation factor
        USRPDecimationFactor = MasterClockRate/config.sdr.FrontEndSampleRate;
%         USRPDecimationFactor = 50; 
        
        SDR = comm.SDRuReceiver(...
            'Platform',             platform, ...
            'IPAddress',            address, ...
            'CenterFrequency',      config.sdr.fc, ...
            'Gain',                 config.sdr.gain, ...
            'DecimationFactor',     USRPDecimationFactor, ...
            'SamplesPerFrame',      config.FrameLength, ...
            'MasterClockRate',      MasterClockRate, ...
            'OutputDataType',       'double');
        
        factor = 40 + config.sdr.gain;
        
    case {'b200', 'b210', 'b200_mini'} % Create USRP SDR receiver
        
        sdr_info = findsdru();
        serialNum = sdr_info.SerialNum; % IP address of the USRP
        platform = sdr_info.Platform;
        MasterClockRate = 32e6; % default 32 MHz
        % Baseband sample rate = Master clock rate/Decimation factor
        USRPDecimationFactor = MasterClockRate/config.sdr.FrontEndSampleRate;
%         USRPDecimationFactor = 50; 
        
        SDR = comm.SDRuReceiver(...
            'Platform',  platform, ...
            'SerialNum', serialNum,...
            'CenterFrequency',      config.sdr.fc, ...
            'Gain',                 config.sdr.gain, ...
            'DecimationFactor',     USRPDecimationFactor, ...
            'SamplesPerFrame',      config.FrameLength, ...
            'MasterClockRate',      MasterClockRate, ...
            'OutputDataType',       'double');
        
        factor = 40 + config.sdr.gain;


    case 'pluto' 
       
       SDR = comm.SDRRxPluto(...
             'RadioID','usb:0',...
           'CenterFrequency',config.sdr.fc, ...
           'BasebandSampleRate',config.sdr.FrontEndSampleRate,...
           'GainSource', 'Manual',...
           'Gain', config.sdr.gain,...
           'ShowAdvancedProperties', true, ...
           'EnableRFDCCorrection', true, ...
           'EnableBasebandDCCorrection', true, ...
           'EnableQuadratureCorrection', true, ...
           'SamplesPerFrame', config.FrameLength, ...
           'OutputDataType','double');
       
       
         factor = 25 + config.sdr.gain;
    
    case 'zedboard'     
        SDR = comm.SDRRxAD936x(...
           'IPAddress','192.168.3.2',...
           'CenterFrequency',config.sdr.fc, ...
           'BasebandSampleRate',config.sdr.FrontEndSampleRate,...
           'GainSource', 'Manual',...
           'Gain', config.sdr.gain,...
           'ShowAdvancedProperties', true, ...
           'SamplesPerFrame', config.FrameLength, ...
           'OutputDataType','double');
       
       
         factor = 25 + config.sdr.gain;
    otherwise
        error('Undefined SDR Type!')
        
end

end

